---
title: Introduction to R
---

On this page you will find links to the data we need for the course, as well as course notes for each of the modules

#### Course Notes
[00 - Basics](00-basics.html) (We didn't actually go through this material, but referenced it as we worked through the other sections)

[01 - Introduction](01-introduction.html) (This was our starting point)

[02 - Starting with Data](02-data_frames.html)

[02 - Data munging with dplyr](02-dplyr.html)

[03 - Plotting](03-plotting.html)

[04 - Basic statistics](04-basic_stats.html)

[05 - Repeating things](05-repeating-things.html)

[06 - Functions](06-functions.html)

[07 - Putting it all together](07-all-together.html)

[08 - Best Practices](08-best-practices.html)

[Getting help](getting_help.html)

#### Data
[Gapminder dataset](data/gapminder-FiveYearData.csv)

[Iris dataset (csv)](data/iris.csv)

[Iris dataset (zip)](data/iris.zip)

#### Credits
Most of the material here was borrowed and adapted from 
[Software Carpentry](http://www.softwarecarpentry.org)'s
[novice R Bootcamp material](https://github.com/swcarpentry/bc/tree/master/novice/r), 
which they make available for reuse under the Creative Commons Attribution [(CC_BY)](http://creativecommons.org/licenses/by/3.0/) license. 
These are amazing people, doing amazing things to help the scientific world be 
more productive with their code and data. Check them out, and if you get the chance 
to attend a bootcamp, do it.

The [course notes](http://www.poissonconsulting.ca/courses/2012/06/05/an-introduction-to-r-course-12.html) from [Poisson Consulting](http://www.poissonconsulting.ca/)'s 
2012 R Course were also very helpful in putting this material together.

Much of the `dplyr` material came from the dplyr [package vignette](http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html).

When we went off-roading to play with the reshape2 package, we used material from 
[this website](http://seananderson.ca/2013/10/19/reshape.html).

#### Source
Source material for the website can be found here: https://github.com/ateucher/rcourse_site

#### PDF
Download the entire course notes package as a pdf [here](pdf/Intro_R_ATeucher.pdf)

#### License
Notes: [CC-BY](http://creativecommons.org/licenses/by/3.0/). Code: [MIT](http://opensource.org/licenses/mit-license.html)

#### Parting shot: [Nice Job!](high-five.html)
